### ISSUE TITLE
Theme expand by default not working

### ISSUE THREAD

**Issue by brianjo** [pytorch/pytorch_sphinx_theme#98] opened 2021-03-02 14:20 UTC
The expand by default code doesn't seem to be working. Is there a way we can set that in script without having to rebuild the whole documentation set? 

Also, when a user clicks a heading and goes to the new page, the section is again collapsed. It would be optimal if that stayed open on click. 

Could we possibly use a cookie to save expand/collapse state for the user? That might be best for everything. 

See the note in https://github.com/pytorch/tutorials/pull/1372 and the new PR https://github.com/pytorch/pytorch_sphinx_theme/pull/97. 

@Bgreen23

**Comment by Bgreen23** [comment] 2021-03-02 17:01
Hey @brianjo,

https://github.com/pytorch/pytorch/pull/52703 needs to be merged in for the Docs and then the documentation set will need to be rebuilt in order to add the script to the Docs and Tutorials. 

> when a user clicks a heading and goes to the new page, the section is again collapsed. It would be optimal if that stayed open on click.

The current implementation will collapse sections when a user reloads the page or navigates to a new page. I can work on implementing a change where the state of the section stays the same on a new page.

**Comment by brianjo** [comment] 2021-03-03 15:43
@Bgreen23 Hi Brandon, It's landed for tutorials here: https://github.com/pytorch/tutorials/blob/master/_templates/layout.html but we're not seeing the correct behavior when the page is loaded. It's all live now there. I haven't merged docs because I want to fix the expand/collapse persistence issue and I'm thinking about rolling back the theme on docs. Thanks!

**Comment by Bgreen23** [comment] 2021-03-03 18:15
@brianjo It looks like the theme needs to be re-built/updated with the updates from this [PR](https://github.com/pytorch/pytorch_sphinx_theme/pull/96). Once the theme is updated, then everything should be working as expected.

**Comment by brianjo** [comment] 2021-03-03 18:25
So this is what is in our requirements.txt when we build tutorials: 
```
-e git+git://github.com/pytorch/pytorch_sphinx_theme.git#egg=pytorch_sphinx_theme
```
And this is a preview I just ran a while ago: 
https://deploy-preview-1377--pytorch-tutorials-preview.netlify.app/

Can you tell if I'm missing something? 

Also please see https://github.com/pytorch/pytorch_sphinx_theme/pull/97, and let me know if that would fix it? (The theme is used by bunch of different projects and so it looks like I'm not the only one seeing the issue.) 

Thanks!

**Comment by Bgreen23** [comment] 2021-03-03 18:50
I'm seeing the outdated expand/collapsed function in your preview when I view the `theme.js`(see screenshot attached). The outdated function doesn't include `collapsedSections` which is why it's not working as intended. This lines up with how [#97](https://github.com/pytorch/pytorch_sphinx_theme/pull/97) solved their issue by running `grunt build`. Let me know if that clears anything up and if you have any additional questions!

![Screen Shot 2021-03-03 at 1 34 13 PM](https://user-images.githubusercontent.com/31549535/109854819-7f852b00-7c25-11eb-9c5c-673951a79529.png)

**Comment by brianjo** [comment] 2021-03-03 19:05
Sorry, the solution to this isn't clear to me. Should I merge #97 to fix the issue?

**Closed as completed** 2021-03-08 20:53 UTC
